from effects.base_effect import BaseEffect
from effects.effect1 import Effect1
from effects.effect2 import Effect2
from effects.effect3 import Effect3
from effects.effect4 import Effect4
from effects.effect5 import Effect5
from effects.effect6 import Effect6
from effects.effect7 import Effect7
from effects.effect8 import Effect8
from effects.effect9 import Effect9
from effects.effect10 import Effect10
from effects.effect11 import Effect11
from effects.effect12 import Effect12
from effects.effect13 import Effect13
from effects.effect14 import Effect14
from effects.effect15 import Effect15
from effects.effect16 import Effect16
from effects.effect17 import Effect17
from effects.effect18 import Effect18
from effects.effect19 import Effect19
from effects.effect20 import Effect20
from effects.effect21 import Effect21
from effects.effect22 import Effect22
from effects.effect23 import Effect23
from effects.effect24 import Effect24